# Generated by Django 5.2.14 on 2026-05-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('source', models.CharField(max_length=180)),
                ('unit', models.CharField(max_length=40)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=14)),
                ('scope', models.CharField(max_length=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=180)),
                ('country', models.CharField(default='US', max_length=2)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('grid_region', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('ingestion_mode', models.CharField(max_length=80)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_id', models.CharField(max_length=180)),
                ('payload', models.JSONField(default=dict)),
                ('parse_status', models.CharField(default='parsed', max_length=20)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingest.ingestionbatch')),
            ],
            options={
                'unique_together': {('batch', 'source_row_id')},
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('source_reference', models.CharField(max_length=180)),
                ('activity_type', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=10)),
                ('activity_start', models.DateField()),
                ('activity_end', models.DateField()),
                ('original_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('original_unit', models.CharField(max_length=40)),
                ('normalized_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=40)),
                ('kg_co2e', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('data_quality_score', models.PositiveSmallIntegerField(default=100)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='needs_review', max_length=20)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('edited_by', models.CharField(blank=True, max_length=180)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=180)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingest.emissionfactor')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='ingest.facility')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='ingest.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingest.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ingest.sourceconnector'),
        ),
        migrations.AddField(
            model_name='sourceconnector',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='ingest.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingest.tenant'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingest.tenant'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=180)),
                ('action', models.CharField(max_length=80)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingest.activityrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingest.tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sourceconnector',
            unique_together={('tenant', 'source_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'status'], name='ingest_acti_tenant__16ec04_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='ingest_acti_tenant__898f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'scope'], name='ingest_acti_tenant__a53150_idx'),
        ),
    ]
