services:
  - type: web
    name: breathe-esg-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py seed_demo && python manage.py collectstatic --noinput"
    startCommand: "gunicorn breathe.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "0"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "1"
      - key: SECRET_KEY
        generateValue: true
